import npp640 from '../assets/images/hero/npp-640.webp?url';
import npp960 from '../assets/images/hero/npp-960.webp?url';
import npp1280 from '../assets/images/hero/npp-1280.webp?url';
import npp1920 from '../assets/images/hero/npp-1920.webp?url';

/**
 * The homepage hero, which is the LCP element.
 *
 * Defined here rather than inside the component so BaseLayout can emit a
 * matching `<link rel="preload">`. The preload has to reference the exact same
 * srcset/sizes the browser will choose from, otherwise it fetches a second copy
 * instead of priming the one the `<img>` uses.
 *
 * The image spans the full viewport width, so without a srcset every phone would
 * download the 1920px original (179KB); the 640px variant is ~27KB. Variants are
 * generated by scripts/generate-hero-images.mjs and imported as URLs so Vite
 * fingerprints them into /_astro/ for immutable caching — see that script for
 * why astro:assets isn't used here.
 */
export const heroImage = {
  src: npp1280,
  srcSet: [
    `${npp640} 640w`,
    `${npp960} 960w`,
    `${npp1280} 1280w`,
    `${npp1920} 1920w`,
  ].join(', '),
  sizes: '100vw',
  width: 1920,
  height: 1280,
};
